# Generated by Django 4.0.5 on 2022-06-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greeting',
            old_name='message',
            new_name='Show',
        ),
    ]
